// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	Announcement "be-empower-hr/features/Announcement"

	mock "github.com/stretchr/testify/mock"
)

// AnnoQuery is an autogenerated mock type for the AnnoQuery type
type AnnoQuery struct {
	mock.Mock
}

// Create provides a mock function with given fields: newAnn
func (_m *AnnoQuery) Create(newAnn Announcement.Announcement) error {
	ret := _m.Called(newAnn)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(Announcement.Announcement) error); ok {
		r0 = rf(newAnn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *AnnoQuery) GetAll() ([]Announcement.Announcement, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []Announcement.Announcement
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]Announcement.Announcement, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []Announcement.Announcement); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Announcement.Announcement)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAnnoQuery creates a new instance of AnnoQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnnoQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnnoQuery {
	mock := &AnnoQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
