// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// AnnoHandler is an autogenerated mock type for the AnnoHandler type
type AnnoHandler struct {
	mock.Mock
}

// AddAnnouncement provides a mock function with given fields: c
func (_m *AnnoHandler) AddAnnouncement(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for AddAnnouncement")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAnno provides a mock function with given fields: c
func (_m *AnnoHandler) GetAnno(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetAnno")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAnnoHandler creates a new instance of AnnoHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnnoHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnnoHandler {
	mock := &AnnoHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
