// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	attendance "be-empower-hr/features/Attendance"

	mock "github.com/stretchr/testify/mock"
)

// AQuery is an autogenerated mock type for the AQuery type
type AQuery struct {
	mock.Mock
}

// Create provides a mock function with given fields: newAtt
func (_m *AQuery) Create(newAtt attendance.Attandance) error {
	ret := _m.Called(newAtt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(attendance.Attandance) error); ok {
		r0 = rf(newAtt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAttbyId provides a mock function with given fields: attId
func (_m *AQuery) DeleteAttbyId(attId uint) error {
	ret := _m.Called(attId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAttbyId")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(attId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllAtt provides a mock function with given fields: limit, offset
func (_m *AQuery) GetAllAtt(limit int, offset int) ([]attendance.Attandance, error) {
	ret := _m.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAtt")
	}

	var r0 []attendance.Attandance
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]attendance.Attandance, error)); ok {
		return rf(limit, offset)
	}
	if rf, ok := ret.Get(0).(func(int, int) []attendance.Attandance); ok {
		r0 = rf(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]attendance.Attandance)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllAttDownload provides a mock function with given fields:
func (_m *AQuery) GetAllAttDownload() ([]attendance.Attandance, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllAttDownload")
	}

	var r0 []attendance.Attandance
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]attendance.Attandance, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []attendance.Attandance); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]attendance.Attandance)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAttByPersonalID provides a mock function with given fields: personalID, limit, offset
func (_m *AQuery) GetAttByPersonalID(personalID uint, limit int, offset int) ([]attendance.Attandance, error) {
	ret := _m.Called(personalID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAttByPersonalID")
	}

	var r0 []attendance.Attandance
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, int, int) ([]attendance.Attandance, error)); ok {
		return rf(personalID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(uint, int, int) []attendance.Attandance); ok {
		r0 = rf(personalID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]attendance.Attandance)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, int, int) error); ok {
		r1 = rf(personalID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalAttendancesCount provides a mock function with given fields:
func (_m *AQuery) GetTotalAttendancesCount() (int64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTotalAttendancesCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsDateExists provides a mock function with given fields: personalID, date
func (_m *AQuery) IsDateExists(personalID uint, date string) (bool, error) {
	ret := _m.Called(personalID, date)

	if len(ret) == 0 {
		panic("no return value specified for IsDateExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, string) (bool, error)); ok {
		return rf(personalID, date)
	}
	if rf, ok := ret.Get(0).(func(uint, string) bool); ok {
		r0 = rf(personalID, date)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uint, string) error); ok {
		r1 = rf(personalID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, updatedAtt
func (_m *AQuery) Update(id uint, updatedAtt attendance.Attandance) error {
	ret := _m.Called(id, updatedAtt)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, attendance.Attandance) error); ok {
		r0 = rf(id, updatedAtt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAQuery creates a new instance of AQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *AQuery {
	mock := &AQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
