// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ExcelUtilityInterface is an autogenerated mock type for the ExcelUtilityInterface type
type ExcelUtilityInterface struct {
	mock.Mock
}

// DownloadExcel provides a mock function with given fields: data
func (_m *ExcelUtilityInterface) DownloadExcel(data []struct{}) ([]byte, error) {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for DownloadExcel")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]struct{}) ([]byte, error)); ok {
		return rf(data)
	}
	if rf, ok := ret.Get(0).(func([]struct{}) []byte); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]struct{}) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewExcelUtilityInterface creates a new instance of ExcelUtilityInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExcelUtilityInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExcelUtilityInterface {
	mock := &ExcelUtilityInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
