// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	payroll "be-empower-hr/features/Payroll"

	mock "github.com/stretchr/testify/mock"
)

// ServicePayrollInterface is an autogenerated mock type for the ServicePayrollInterface type
type ServicePayrollInterface struct {
	mock.Mock
}

// CreatePayroll provides a mock function with given fields: _a0
func (_m *ServicePayrollInterface) CreatePayroll(_a0 payroll.PayrollDataEntity) (payroll.PayrollDataEntity, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayroll")
	}

	var r0 payroll.PayrollDataEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(payroll.PayrollDataEntity) (payroll.PayrollDataEntity, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(payroll.PayrollDataEntity) payroll.PayrollDataEntity); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(payroll.PayrollDataEntity)
	}

	if rf, ok := ret.Get(1).(func(payroll.PayrollDataEntity) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllPayroll provides a mock function with given fields:
func (_m *ServicePayrollInterface) GetAllPayroll() ([]payroll.PayrollResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllPayroll")
	}

	var r0 []payroll.PayrollResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]payroll.PayrollResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []payroll.PayrollResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]payroll.PayrollResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPayrollDownload provides a mock function with given fields: ID
func (_m *ServicePayrollInterface) GetPayrollDownload(ID uint) error {
	ret := _m.Called(ID)

	if len(ret) == 0 {
		panic("no return value specified for GetPayrollDownload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewServicePayrollInterface creates a new instance of ServicePayrollInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServicePayrollInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServicePayrollInterface {
	mock := &ServicePayrollInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
